"""
Copyright (c) 2020 Bahareh Tolooshams

config

:author: Bahareh Tolooshams
"""

import torch

from sacred import Experiment, Ingredient

config_ingredient = Ingredient("cfg")

use_cuda = torch.cuda.is_available()
device = torch.device("cuda:0" if use_cuda else "cpu")


@config_ingredient.config
def cfg():
    hyp = {
        "experiment_name": "default",
        "dataset": "MNIST",
        "network": "CRsAE2D",
        "dictionary_dim": 5,
        "num_conv": 64,
        "stride": 6,
        "L": 100,
        "trainable_bias": False,
        "delta": 50,
        "num_iters": 50,
        "batch_size": 16,
        "num_epochs": 20,
        "normalize": True,
        "lr": 5e-4,
        "lr_decay": 0.7,
        "lr_step": 10,
        "lr_lam": 1e-2,
        "cyclic": False,
        "noiseSTD": 20,
        "shuffle": True,
        "test_path": "../data/test_img/",
        "train_path": "../data/test_img/",
        "device": device,
        "warm_start": True,
        "info_period": 10,
        "denoising": True,
        "supervised": True,
        "crop_dim": (250, 250),
        "init_with_DCT": True,
        "init_with_saved_file": False,
        "sigma": 0.18,
        "loss": "MSE",
        "lam": 0.1,
        "twosided": True,
        "image_set": "train",
        "year": "2012",
        "segmentation": True,
    }


################################
################################
@config_ingredient.named_config
def crsae_kernel7_conv64_stride5_ista30_lam015():
    hyp = {
        "experiment_name": "crsae_kernel7_conv64_stride5_ista30_lam015",
        "dataset": "VOC",
        "image_set": "train",
        "year": "2012",
        "segmentation": False,
        "network": "CRsAE2DFreeBias",
        "dictionary_dim": 7,
        "stride": 5,
        "num_conv": 64,
        "L": 10,
        "num_iters": 30,
        "batch_size": 1,
        "num_epochs": 200,
        "normalize": True,
        "lr": 0.01,
        "lr_decay": 0.7,
        "lr_step": 10,
        "noiseSTD": 20,
        "shuffle": True,
        "test_path": "../data/test_img/",
        "info_period": 2000,
        "denoising": True,
        "supervised": True,
        "crop_dim": (128, 128),
        "init_with_DCT": False,
        "init_with_saved_file": False,
        "loss": "MSE",
        "trainable_bias": False,
        "lam": 0.15,
    }

@config_ingredient.named_config
def crsae_kernel7_conv64_stride5_ista30_fix_lam015():
    hyp = {
        "experiment_name": "crsae_kernel7_conv64_stride5_ista30_fix_lam015",
        "dataset": "VOC",
        "image_set": "train",
        "year": "2012",
        "segmentation": False,
        "network": "CRsAE2D",
        "dictionary_dim": 7,
        "stride": 5,
        "num_conv": 64,
        "L": 10,
        "num_iters": 30,
        "batch_size": 1,
        "num_epochs": 200,
        "normalize": True,
        "lr": 0.01,
        "lr_decay": 0.7,
        "lr_step": 10,
        "noiseSTD": 20,
        "shuffle": True,
        "test_path": "../data/test_img/",
        "info_period": 2000,
        "denoising": True,
        "supervised": True,
        "crop_dim": (128, 128),
        "init_with_DCT": False,
        "init_with_saved_file": False,
        "loss": "MSE",
        "trainable_bias": False,
        "lam": 0.15,
    }


@config_ingredient.named_config
def crsae_kernel7_conv64_stride5_ista30_em_20():
    hyp = {
        "experiment_name": "crsae_kernel7_conv64_stride5_ista30_em_20",
        "dataset": "VOC",
        "image_set": "train",
        "year": "2012",
        "segmentation": False,
        "network": "CRsAE2DTrainableBias",
        "dictionary_dim": 7,
        "stride": 5,
        "num_conv": 64,
        "L": 10,
        "num_iters": 30,
        "batch_size": 1,
        "num_epochs": 250,
        "normalize": False,
        "lr": 0.01,
        "lr_lam": 0.1,
        "lr_decay": 0.7,
        "lr_step": 10,
        "noiseSTD": 20,
        "sigma": 0.078,
        "shuffle": True,
        "test_path": "../data/test_img/",
        "info_period": 2000,
        "denoising": True,
        "supervised": True,
        "crop_dim": (128, 128),
        "init_with_DCT": False,
        "init_with_saved_file": False,
        "loss": "MSE",
        "trainable_bias": True,
        "lam": 20,
        "delta": 100,
    }


@config_ingredient.named_config
def crsae_kernel7_conv64_stride5_ista3_em_20():
    hyp = {
        "experiment_name": "crsae_kernel7_conv64_stride5_ista3_em_20",
        "dataset": "VOC",
        "image_set": "train",
        "year": "2012",
        "segmentation": False,
        "network": "CRsAE2DTrainableBias",
        "dictionary_dim": 7,
        "stride": 5,
        "num_conv": 64,
        "L": 10,
        "num_iters": 3,
        "batch_size": 1,
        "num_epochs": 250,
        "normalize": True,
        "lr": 0.01,
        "lr_lam": 0.1,
        "lr_decay": 0.7,
        "lr_step": 10,
        "noiseSTD": 20,
        "sigma": 0.078,
        "shuffle": True,
        "test_path": "../data/test_img/",
        "info_period": 2000,
        "denoising": True,
        "supervised": True,
        "crop_dim": (128, 128),
        "init_with_DCT": False,
        "init_with_saved_file": False,
        "loss": "MSE",
        "trainable_bias": True,
        "lam": 20,
        "delta": 100,
    }

@config_ingredient.named_config
def crsae_kernel7_conv64_stride5_ista30_em_20_untied():
    hyp = {
        "experiment_name": "crsae_kernel7_conv64_stride5_ista30_em_20_untied",
        "dataset": "VOC",
        "image_set": "train",
        "year": "2012",
        "segmentation": False,
        "network": "CRsAE2DUntiedTrainableBias",
        "dictionary_dim": 7,
        "stride": 5,
        "num_conv": 64,
        "L": 10,
        "num_iters": 30,
        "batch_size": 1,
        "num_epochs": 250,
        "normalize": False,
        "lr": 0.01,
        "lr_lam": 0.1,
        "lr_decay": 0.7,
        "lr_step": 10,
        "noiseSTD": 20,
        "sigma": 0.078,
        "shuffle": True,
        "test_path": "../data/test_img/",
        "info_period": 2000,
        "denoising": True,
        "supervised": True,
        "crop_dim": (128, 128),
        "init_with_DCT": False,
        "init_with_saved_file": False,
        "loss": "MSE",
        "trainable_bias": True,
        "lam": 20,
        "delta": 100,
    }

@config_ingredient.named_config
def crsae_kernel7_conv64_stride5_ista30_em_20_untied_normalized():
    hyp = {
        "experiment_name": "crsae_kernel7_conv64_stride5_ista30_em_20_untied_normalized",
        "dataset": "VOC",
        "image_set": "train",
        "year": "2012",
        "segmentation": False,
        "network": "CRsAE2DUntiedTrainableBias",
        "dictionary_dim": 7,
        "stride": 5,
        "num_conv": 64,
        "L": 10,
        "num_iters": 30,
        "batch_size": 1,
        "num_epochs": 300,
        "normalize": True,
        "lr": 0.01,
        "lr_lam": 0.1,
        "lr_decay": 0.7,
        "lr_step": 10,
        "noiseSTD": 20,
        "sigma": 0.078,
        "shuffle": True,
        "test_path": "../data/test_img/",
        "info_period": 2000,
        "denoising": True,
        "supervised": True,
        "crop_dim": (128, 128),
        "init_with_DCT": False,
        "init_with_saved_file": False,
        "loss": "MSE",
        "trainable_bias": True,
        "lam": 20,
        "delta": 100,
    }

@config_ingredient.named_config
def crsae_kernel7_conv64_stride5_ista30_em_20_untied_normalized_msssim():
    hyp = {
        "experiment_name": "crsae_kernel7_conv64_stride5_ista30_em_20_untied_normalized_msssim",
        "dataset": "VOC",
        "image_set": "train",
        "year": "2012",
        "segmentation": False,
        "network": "CRsAE2DUntiedTrainableBias",
        "dictionary_dim": 7,
        "stride": 5,
        "num_conv": 64,
        "L": 10,
        "num_iters": 30,
        "batch_size": 1,
        "num_epochs": 300,
        "normalize": True,
        "lr": 0.01,
        "lr_lam": 0.1,
        "lr_decay": 0.7,
        "lr_step": 10,
        "noiseSTD": 20,
        "sigma": 0.078,
        "shuffle": True,
        "test_path": "../data/test_img/",
        "info_period": 2000,
        "denoising": True,
        "supervised": True,
        "crop_dim": (128, 128),
        "init_with_DCT": False,
        "init_with_saved_file": False,
        "loss": "MSSSIM_l1",
        "trainable_bias": True,
        "lam": 20,
        "delta": 100,
    }

@config_ingredient.named_config
def crsae_kernel7_conv64_stride5_ista30_em_20_untied_normalized_msssim_smllr():
    hyp = {
        "experiment_name": "crsae_kernel7_conv64_stride5_ista30_em_20_untied_normalized_msssim_smllr",
        "dataset": "VOC",
        "image_set": "train",
        "year": "2012",
        "segmentation": False,
        "network": "CRsAE2DUntiedTrainableBias",
        "dictionary_dim": 7,
        "stride": 5,
        "num_conv": 64,
        "L": 10,
        "num_iters": 30,
        "batch_size": 1,
        "num_epochs": 300,
        "normalize": True,
        "lr": 0.0001,
        "lr_lam": 0.1,
        "lr_decay": 0.7,
        "lr_step": 10,
        "noiseSTD": 20,
        "sigma": 0.078,
        "shuffle": True,
        "test_path": "../data/test_img/",
        "info_period": 2000,
        "denoising": True,
        "supervised": True,
        "crop_dim": (128, 128),
        "init_with_DCT": False,
        "init_with_saved_file": False,
        "loss": "MSSSIM_l1",
        "trainable_bias": True,
        "lam": 20,
        "delta": 100,
    }


@config_ingredient.named_config
def crsae_kernel7_conv64_stride5_ista30_untied():
    hyp = {
        "experiment_name": "crsae_kernel7_conv64_stride5_ista30_untied",
        "dataset": "VOC",
        "image_set": "train",
        "year": "2012",
        "segmentation": False,
        "network": "CRsAE2DUntiedFreeBias",
        "dictionary_dim": 7,
        "stride": 5,
        "num_conv": 64,
        "L": 10,
        "num_iters": 30,
        "batch_size": 1,
        "num_epochs": 300,
        "normalize": True,
        "lr": 0.01,
        "lr_decay": 0.7,
        "lr_step": 10,
        "noiseSTD": 20,
        "sigma": 0.078,
        "shuffle": True,
        "test_path": "../data/test_img/",
        "info_period": 2000,
        "denoising": True,
        "supervised": True,
        "crop_dim": (128, 128),
        "init_with_DCT": False,
        "init_with_saved_file": False,
        "loss": "MSE",
        "trainable_bias": False,
        "lam": 0.15,
    }





@config_ingredient.named_config
def lcsc_kernel7_conv64_stride1_ista30():
    hyp = {
        "experiment_name": "lcsc_kernel7_conv64_stride1_ista30",
        "dataset": "VOC",
        "image_set": "train",
        "year": "2012",
        "segmentation": False,
        "network": "LCSC2D",
        "dictionary_dim": 7,
        "stride": 1,
        "num_conv": 64,
        "L": 10,
        "num_iters": 30,
        "batch_size": 1,
        "num_epochs": 200,
        "normalize": False,
        "lr": 0.001,
        "lr_decay": 0.7,
        "lr_step": 10,
        "noiseSTD": 20,
        "shuffle": True,
        "test_path": "../data/test_img/",
        "info_period": 2000,
        "denoising": True,
        "supervised": True,
        "crop_dim": (128, 128),
        "init_with_DCT": False,
        "init_with_saved_file": False,
        "loss": "MSE",
        "trainable_bias": False,
        "lam": 0.15,
    }


#####


@config_ingredient.named_config
def lcsc_kernel7_conv64_stride1_ista15():
    hyp = {
        "experiment_name": "lcsc_kernel7_conv64_stride1_ista15",
        "dataset": "VOC",
        "image_set": "train",
        "year": "2012",
        "segmentation": False,
        "network": "LCSC2D",
        "dictionary_dim": 7,
        "stride": 1,
        "num_conv": 64,
        "L": 100,
        "num_iters": 15,
        "batch_size": 1,
        "num_epochs": 400,
        "normalize": False,
        "lr": 0.001,
        "lr_decay": 0.8,
        "lr_step": 15,
        "noiseSTD": 20,
        "shuffle": True,
        "test_path": "../data/test_img/",
        "info_period": 2000,
        "denoising": True,
        "supervised": True,
        "crop_dim": (128, 128),
        "init_with_DCT": False,
        "init_with_saved_file": False,
        "loss": "MSE",
        "trainable_bias": False,
        "lam": 1,
    }


@config_ingredient.named_config
def lcsc_kernel7_conv64_stride5_ista15():
    hyp = {
        "experiment_name": "crsae_kernel7_conv64_stride5_ista15",
        "dataset": "VOC",
        "image_set": "train",
        "year": "2012",
        "segmentation": False,
        "network": "LCSC2D",
        "dictionary_dim": 7,
        "stride": 5,
        "num_conv": 64,
        "L": 10,
        "num_iters": 15,
        "batch_size": 1,
        "num_epochs": 400,
        "normalize": False,
        "lr": 0.001,
        "lr_decay": 0.8,
        "lr_step": 15,
        "noiseSTD": 20,
        "shuffle": True,
        "test_path": "../data/test_img/",
        "info_period": 2000,
        "denoising": True,
        "supervised": True,
        "crop_dim": (128, 128),
        "init_with_DCT": False,
        "init_with_saved_file": False,
        "loss": "MSE",
        "trainable_bias": False,
        "lam": 1,
    }


@config_ingredient.named_config
def crsae_kernel8_conv64_stride7_ista30():
    hyp = {
        "experiment_name": "crsae_kernel8_conv64_stride7_ista30",
        "dataset": "VOC",
        "image_set": "train",
        "year": "2012",
        "segmentation": False,
        "network": "CRsAE2DFreeBias",
        "dictionary_dim": 8,
        "stride": 7,
        "num_conv": 64,
        "L": 50,
        "num_iters": 30,
        "batch_size": 1,
        "num_epochs": 200,
        "normalize": True,
        "lr": 0.1,
        "lr_decay": 0.7,
        "lr_step": 10,
        "noiseSTD": 20,
        "shuffle": True,
        "test_path": "../data/test_img/",
        "info_period": 2000,
        "denoising": True,
        "supervised": True,
        "crop_dim": (128, 128),
        "init_with_DCT": True,
        "init_with_saved_file": False,
        "loss": "MSE",
        "trainable_bias": False,
        "lam": 1,
    }


@config_ingredient.named_config
def crsae_kernel8_conv64_stride7_ista30_lam015():
    hyp = {
        "experiment_name": "crsae_kernel8_conv64_stride7_ista30_lam015",
        "dataset": "VOC",
        "image_set": "train",
        "year": "2012",
        "segmentation": False,
        "network": "CRsAE2DFreeBias",
        "dictionary_dim": 8,
        "stride": 7,
        "num_conv": 64,
        "L": 50,
        "num_iters": 30,
        "batch_size": 1,
        "num_epochs": 200,
        "normalize": True,
        "lr": 0.01,
        "lr_decay": 0.7,
        "lr_step": 10,
        "noiseSTD": 20,
        "shuffle": True,
        "test_path": "../data/test_img/",
        "info_period": 2000,
        "denoising": True,
        "supervised": True,
        "crop_dim": (128, 128),
        "init_with_DCT": True,
        "init_with_saved_file": False,
        "loss": "MSE",
        "trainable_bias": False,
        "lam": 0.15,
    }


@config_ingredient.named_config
def crsae_kernel8_conv144_stride6_ista30_lam015():
    hyp = {
        "experiment_name": "crsae_kernel8_conv144_stride6_ista30_lam015",
        "dataset": "VOC",
        "image_set": "train",
        "year": "2012",
        "segmentation": False,
        "network": "CRsAE2DFreeBias",
        "dictionary_dim": 8,
        "stride": 6,
        "num_conv": 144,
        "L": 50,
        "num_iters": 30,
        "batch_size": 1,
        "num_epochs": 200,
        "normalize": True,
        "lr": 0.01,
        "lr_decay": 0.7,
        "lr_step": 10,
        "noiseSTD": 20,
        "shuffle": True,
        "test_path": "../data/test_img/",
        "info_period": 2000,
        "denoising": True,
        "supervised": True,
        "crop_dim": (128, 128),
        "init_with_DCT": False,
        "init_with_saved_file": False,
        "loss": "MSE",
        "trainable_bias": False,
        "lam": 0.15,
    }


@config_ingredient.named_config
def crsae_kernel8_conv64_stride7_ista30_fixlambda_03():
    hyp = {
        "experiment_name": "crsae_kernel8_conv64_stride7_ista30_fixlambda_03",
        "dataset": "VOC",
        "image_set": "train",
        "year": "2012",
        "segmentation": False,
        "network": "CRsAE2D",
        "dictionary_dim": 8,
        "stride": 7,
        "num_conv": 64,
        "L": 50,
        "num_iters": 30,
        "batch_size": 1,
        "num_epochs": 200,
        "normalize": True,
        "lr": 0.1,
        "lr_decay": 0.7,
        "lr_step": 10,
        "noiseSTD": 20,
        "shuffle": True,
        "test_path": "../data/test_img/",
        "info_period": 2000,
        "denoising": True,
        "supervised": True,
        "crop_dim": (128, 128),
        "init_with_DCT": True,
        "init_with_saved_file": False,
        "loss": "MSE",
        "trainable_bias": False,
        "lam": 0.3,
    }


@config_ingredient.named_config
def crsae_kernel8_conv64_stride7_ista30_fixlambda_015():
    hyp = {
        "experiment_name": "crsae_kernel8_conv64_stride7_ista30_fixlambda_015",
        "dataset": "VOC",
        "image_set": "train",
        "year": "2012",
        "segmentation": False,
        "network": "CRsAE2D",
        "dictionary_dim": 8,
        "stride": 7,
        "num_conv": 64,
        "L": 50,
        "num_iters": 30,
        "batch_size": 1,
        "num_epochs": 200,
        "normalize": True,
        "lr": 0.1,
        "lr_decay": 0.7,
        "lr_step": 10,
        "noiseSTD": 20,
        "shuffle": True,
        "test_path": "../data/test_img/",
        "info_period": 2000,
        "denoising": True,
        "supervised": True,
        "crop_dim": (128, 128),
        "init_with_DCT": True,
        "init_with_saved_file": False,
        "loss": "MSE",
        "trainable_bias": False,
        "lam": 0.15,
    }


@config_ingredient.named_config
def crsae_kernel8_conv144_stride6_ista30_fixlambda_015():
    hyp = {
        "experiment_name": "crsae_kernel8_conv144_stride6_ista30_fixlambda_015",
        "dataset": "VOC",
        "image_set": "train",
        "year": "2012",
        "segmentation": False,
        "network": "CRsAE2D",
        "dictionary_dim": 8,
        "stride": 6,
        "num_conv": 144,
        "L": 50,
        "num_iters": 30,
        "batch_size": 1,
        "num_epochs": 200,
        "normalize": True,
        "lr": 0.01,
        "lr_decay": 0.7,
        "lr_step": 10,
        "noiseSTD": 20,
        "shuffle": True,
        "test_path": "../data/test_img/",
        "info_period": 2000,
        "denoising": True,
        "supervised": True,
        "crop_dim": (128, 128),
        "init_with_DCT": False,
        "init_with_saved_file": False,
        "loss": "MSE",
        "trainable_bias": False,
        "lam": 0.15,
    }


@config_ingredient.named_config
def lcsc_kernel8_conv144_stride6_ista30():
    hyp = {
        "experiment_name": "lcsc_kernel8_conv144_stride6_ista30",
        "dataset": "VOC",
        "image_set": "train",
        "year": "2012",
        "segmentation": False,
        "network": "LCSC2D",
        "dictionary_dim": 8,
        "stride": 6,
        "num_conv": 144,
        "L": 50,
        "num_iters": 30,
        "batch_size": 1,
        "num_epochs": 200,
        "normalize": False,
        "lr": 0.001,
        "lr_decay": 0.7,
        "lr_step": 10,
        "noiseSTD": 20,
        "shuffle": True,
        "test_path": "../data/test_img/",
        "info_period": 2000,
        "denoising": True,
        "supervised": True,
        "crop_dim": (128, 128),
        "init_with_DCT": False,
        "init_with_saved_file": False,
        "loss": "MSE",
        "trainable_bias": False,
        "lam": 0.15,
    }


@config_ingredient.named_config
def lcsc_kernel7_conv64_stride5_ista30():
    hyp = {
        "experiment_name": "lcsc_kernel7_conv64_stride5_ista30",
        "dataset": "VOC",
        "image_set": "train",
        "year": "2012",
        "segmentation": False,
        "network": "LCSC2D",
        "dictionary_dim": 7,
        "stride": 5,
        "num_conv": 64,
        "L": 50,
        "num_iters": 30,
        "batch_size": 1,
        "num_epochs": 200,
        "normalize": False,
        "lr": 0.001,
        "lr_decay": 0.7,
        "lr_step": 10,
        "noiseSTD": 20,
        "shuffle": True,
        "test_path": "../data/test_img/",
        "info_period": 2000,
        "denoising": True,
        "supervised": True,
        "crop_dim": (128, 128),
        "init_with_DCT": False,
        "init_with_saved_file": False,
        "loss": "MSE",
        "trainable_bias": False,
        "lam": 0.15,
    }


@config_ingredient.named_config
def crsae_kernel7_conv64_stride5_ista30_untied_em_20():
    hyp = {
        "experiment_name": "crsae_kernel7_conv64_stride5_ista30_untied_em_20",
        "dataset": "VOC",
        "image_set": "train",
        "year": "2012",
        "segmentation": False,
        "network": "CRsAE2DUntiedTrainableBias",
        "dictionary_dim": 7,
        "stride": 5,
        "num_conv": 64,
        "L": 50,
        "num_iters": 30,
        "batch_size": 1,
        "num_epochs": 200,
        "normalize": True,
        "lr": 0.001,
        "lr_lam": 0.5,
        "lr_decay": 0.8,
        "lr_step": 10,
        "noiseSTD": 20,
        "sigma": 0.078,
        "shuffle": True,
        "test_path": "../data/test_img/",
        "info_period": 200,
        "denoising": True,
        "supervised": True,
        "crop_dim": (128, 128),
        "init_with_DCT": False,
        "init_with_saved_file": False,
        "loss": "MSE",
        "trainable_bias": True,
        "lam": 20,
        "delta": 100,
    }


@config_ingredient.named_config
def crsae_kernel7_conv64_stride5_ista30_untied_em_20_notnorm():
    hyp = {
        "experiment_name": "crsae_kernel7_conv64_stride5_ista30_untied_em_20_notnorm",
        "dataset": "VOC",
        "image_set": "train",
        "year": "2012",
        "segmentation": False,
        "network": "CRsAE2DUntiedTrainableBias",
        "dictionary_dim": 7,
        "stride": 5,
        "num_conv": 64,
        "L": 50,
        "num_iters": 30,
        "batch_size": 1,
        "num_epochs": 200,
        "normalize": False,
        "lr": 0.001,
        "lr_lam": 0.5,
        "lr_decay": 0.8,
        "lr_step": 10,
        "noiseSTD": 20,
        "sigma": 0.078,
        "shuffle": True,
        "test_path": "../data/test_img/",
        "info_period": 200,
        "denoising": True,
        "supervised": True,
        "crop_dim": (128, 128),
        "init_with_DCT": False,
        "init_with_saved_file": False,
        "loss": "MSE",
        "trainable_bias": True,
        "lam": 20,
        "delta": 100,
    }


@config_ingredient.named_config
def crsae_kernel8_conv64_stride7_ista30_em_35():
    hyp = {
        "experiment_name": "crsae_kernel8_conv64_stride7_ista30_em_35",
        "dataset": "VOC",
        "image_set": "train",
        "year": "2012",
        "segmentation": False,
        "network": "CRsAE2DTrainableBias",
        "dictionary_dim": 8,
        "stride": 7,
        "num_conv": 64,
        "L": 50,
        "num_iters": 30,
        "batch_size": 1,
        "num_epochs": 200,
        "normalize": True,
        "lr": 0.1,
        "lr_lam": 0.5,
        "lr_decay": 0.7,
        "lr_step": 10,
        "noiseSTD": 20,
        "sigma": 0.078,
        "shuffle": True,
        "test_path": "../data/test_img/",
        "info_period": 2000,
        "denoising": True,
        "supervised": True,
        "crop_dim": (128, 128),
        "init_with_DCT": True,
        "init_with_saved_file": False,
        "loss": "MSE",
        "trainable_bias": True,
        "lam": 30,
        "delta": 100,
    }


@config_ingredient.named_config
def crsae_kernel8_conv64_stride7_ista30_em_20():
    hyp = {
        "experiment_name": "crsae_kernel8_conv64_stride7_ista30_em_20",
        "dataset": "VOC",
        "image_set": "train",
        "year": "2012",
        "segmentation": False,
        "network": "CRsAE2DTrainableBias",
        "dictionary_dim": 8,
        "stride": 7,
        "num_conv": 64,
        "L": 50,
        "num_iters": 30,
        "batch_size": 1,
        "num_epochs": 200,
        "normalize": True,
        "lr": 0.1,
        "lr_lam": 0.5,
        "lr_decay": 0.7,
        "lr_step": 10,
        "noiseSTD": 20,
        "sigma": 0.078,
        "shuffle": True,
        "test_path": "../data/test_img/",
        "info_period": 2000,
        "denoising": True,
        "supervised": True,
        "crop_dim": (128, 128),
        "init_with_DCT": True,
        "init_with_saved_file": False,
        "loss": "MSE",
        "trainable_bias": True,
        "lam": 20,
        "delta": 100,
    }


@config_ingredient.named_config
def crsae_kernel8_conv144_stride6_ista30_em_20():
    hyp = {
        "experiment_name": "crsae_kernel8_conv144_stride6_ista30_em_20",
        "dataset": "VOC",
        "image_set": "train",
        "year": "2012",
        "segmentation": False,
        "network": "CRsAE2DTrainableBias",
        "dictionary_dim": 8,
        "stride": 6,
        "num_conv": 144,
        "L": 50,
        "num_iters": 30,
        "batch_size": 1,
        "num_epochs": 200,
        "normalize": False,
        "lr": 0.01,
        "lr_lam": 0.5,
        "lr_decay": 0.7,
        "lr_step": 10,
        "noiseSTD": 20,
        "sigma": 0.078,
        "shuffle": True,
        "test_path": "../data/test_img/",
        "info_period": 2000,
        "denoising": True,
        "supervised": True,
        "crop_dim": (128, 128),
        "init_with_DCT": False,
        "init_with_saved_file": False,
        "loss": "MSE",
        "trainable_bias": True,
        "lam": 20,
        "delta": 100,
    }


@config_ingredient.named_config
def crsae_kernel8_conv144_stride6_ista3_em_20():
    hyp = {
        "experiment_name": "crsae_kernel8_conv144_stride6_ista3_em_20",
        "dataset": "VOC",
        "image_set": "train",
        "year": "2012",
        "segmentation": False,
        "network": "CRsAE2DTrainableBias",
        "dictionary_dim": 8,
        "stride": 6,
        "num_conv": 144,
        "L": 50,
        "num_iters": 3,
        "batch_size": 1,
        "num_epochs": 200,
        "normalize": True,
        "lr": 0.01,
        "lr_lam": 0.5,
        "lr_decay": 0.7,
        "lr_step": 10,
        "noiseSTD": 20,
        "sigma": 0.078,
        "shuffle": True,
        "test_path": "../data/test_img/",
        "info_period": 2000,
        "denoising": True,
        "supervised": True,
        "crop_dim": (128, 128),
        "init_with_DCT": False,
        "init_with_saved_file": False,
        "loss": "MSE",
        "trainable_bias": True,
        "lam": 20,
        "delta": 100,
    }


@config_ingredient.named_config
def unsupervised_crsae_test():
    hyp = {
        "experiment_name": "unsupervised_crsae_test",
        "dataset": "path",
        "test_path": "../data/lena/",
        "network": "CRsAE2DTrainableBias",
        "dictionary_dim": 7,
        "stride": 5,
        "num_conv": 169,
        "L": 50,
        "num_iters": 50,
        "batch_size": 1,
        "num_epochs": 400,
        "normalize": False,
        "lr": 0.01,
        "lr_lam": 0.5,
        "lr_decay": 0.9,
        "lr_step": 40,
        "noiseSTD": 20,
        "sigma": 0.078,
        "shuffle": True,
        "test_path": "../data/lena/",
        "info_period": 500,
        "denoising": True,
        "supervised": False,
        "crop_dim": (128, 128),
        "init_with_DCT": True,
        "init_with_saved_file": False,
        "loss": "MSE",
        "trainable_bias": True,
        "lam": 10,
        "delta": 100000,
    }


@config_ingredient.named_config
def crsae_kernel7_conv91_stride5_ista15():
    hyp = {
        "experiment_name": "crsae_kernel7_conv91_stride5_ista15",
        "dataset": "VOC",
        "image_set": "train",
        "year": "2012",
        "segmentation": False,
        "network": "CRsAE2DFreeBias",
        "dictionary_dim": 7,
        "stride": 5,
        "num_conv": 91,
        "L": 10,
        "num_iters": 15,
        "batch_size": 1,
        "num_epochs": 400,
        "normalize": False,
        "lr": 0.001,
        "lr_decay": 0.8,
        "lr_step": 15,
        "noiseSTD": 20,
        "shuffle": True,
        "test_path": "../data/test_img/",
        "info_period": 2000,
        "denoising": True,
        "supervised": True,
        "crop_dim": (128, 128),
        "init_with_DCT": False,
        "init_with_saved_file": False,
        "loss": "MSE",
        "trainable_bias": False,
        "lam": 1,
    }


@config_ingredient.named_config
def crsae_kernel9_conv115_stride7_ista15():
    hyp = {
        "experiment_name": "crsae_kernel9_conv115_stride7_ista15",
        "dataset": "VOC",
        "image_set": "train",
        "year": "2012",
        "segmentation": False,
        "network": "CRsAE2DFreeBias",
        "dictionary_dim": 9,
        "stride": 7,
        "num_conv": 115,
        "L": 10,
        "num_iters": 15,
        "batch_size": 1,
        "num_epochs": 400,
        "normalize": True,
        "lr": 0.001,
        "lr_decay": 0.8,
        "lr_step": 15,
        "noiseSTD": 20,
        "shuffle": True,
        "test_path": "../data/test_img/",
        "info_period": 2000,
        "denoising": True,
        "supervised": True,
        "crop_dim": (128, 128),
        "init_with_DCT": False,
        "init_with_saved_file": False,
        "loss": "MSE",
        "trainable_bias": False,
        "lam": 1,
    }


@config_ingredient.named_config
def crsae_kernel9_conv115_stride7_ista3():
    hyp = {
        "experiment_name": "crsae_kernel9_conv115_stride7_ista3",
        "dataset": "VOC",
        "image_set": "train",
        "year": "2012",
        "segmentation": False,
        "network": "CRsAE2DFreeBias",
        "dictionary_dim": 9,
        "stride": 7,
        "num_conv": 115,
        "L": 10,
        "num_iters": 3,
        "batch_size": 1,
        "num_epochs": 400,
        "normalize": True,
        "lr": 0.001,
        "lr_decay": 0.8,
        "lr_step": 15,
        "noiseSTD": 20,
        "shuffle": True,
        "test_path": "../data/test_img/",
        "info_period": 2000,
        "denoising": True,
        "supervised": True,
        "crop_dim": (128, 128),
        "init_with_DCT": False,
        "init_with_saved_file": False,
        "loss": "MSE",
        "trainable_bias": False,
        "lam": 1,
    }


@config_ingredient.named_config
def unsupervised_crsae_kernel7_conv189_stride5_ista15():
    hyp = {
        "experiment_name": "unsupervised_crsae_kernel7_conv189_stride5_ista15",
        "dataset": "path",
        "segmentation": False,
        "network": "CRsAE2DTrainableBias",
        "dictionary_dim": 7,
        "stride": 5,
        "num_conv": 189,
        "L": 50,
        "num_iters": 15,
        "batch_size": 1,
        "num_epochs": 200,
        "normalize": True,
        "lr": 0.01,
        "lr_decay": 0.9,
        "lr_step": 50,
        "lr_lam": 0.5,
        "noiseSTD": 20,
        "shuffle": True,
        "test_path": "../data/lena/",
        "train_path": "../data/lena/",
        "info_period": 2000,
        "denoising": True,
        "supervised": True,
        "crop_dim": (128, 128),
        "init_with_DCT": False,
        "init_with_saved_file": False,
        "loss": "MSE",
        "trainable_bias": True,
        "delta": 20,  # 50
        "sigma": 0.18,
        "lam": 1,
    }


@config_ingredient.named_config
def lcsc_kernel7_conv64_stride1_ista3():
    hyp = {
        "experiment_name": "lcsc_kernel7_conv64_stride1_ista3",
        "dataset": "VOC",
        "image_set": "train",
        "year": "2012",
        "segmentation": False,
        "network": "LCSC2D",
        "dictionary_dim": 7,
        "stride": 1,
        "num_conv": 64,
        "L": 10,
        "num_iters": 3,
        "batch_size": 1,
        "num_epochs": 200,
        "normalize": False,
        "lr": 0.001,
        "lr_decay": 0.8,
        "lr_step": 15,
        "noiseSTD": 20,
        "shuffle": True,
        "test_path": "../data/test_img/",
        "info_period": 2000,
        "denoising": True,
        "supervised": True,
        "crop_dim": (128, 128),
        "init_with_DCT": False,
        "init_with_saved_file": False,
        "loss": "MSE",
        "trainable_bias": False,
        "lam": 1,
    }


@config_ingredient.named_config
def test_crsae_kernel8_conv64_stride6_fista15():
    hyp = {
        "experiment_name": "test_crsae_kernel8_conv64_stride6_fista15",
        "dataset": "VOC",
        "image_set": "train",
        "year": "2012",
        "segmentation": False,
        "network": "LCSC2D",
        "dictionary_dim": 7,
        "stride": 1,
        "num_conv": 64,
        "L": 10,
        "num_iters": 3,
        "batch_size": 1,
        "num_epochs": 100,
        "normalize": False,
        "lr": 0.01,
        "lr_decay": 0.9,
        "lr_step": 15,
        "noiseSTD": 20,
        "shuffle": True,
        "test_path": "../data/test_img/",
        "info_period": 2000,
        "denoising": True,
        "supervised": True,
        "crop_dim": (128, 128),
        "init_with_DCT": False,
        "init_with_saved_file": False,
        "loss": "MSE",
        "trainable_bias": False,
        "lam": 1,
    }


@config_ingredient.named_config
def crsae_kernel8_conv64_stride6_trainablelam():
    hyp = {
        "experiment_name": "crsae_kernel8_conv64_stride6_trainablelam",
        "dataset": "VOC",
        "network": "CRsAE2DTrainableBias",
        "dictionary_dim": 8,
        "stride": 6,
        "num_conv": 64,
        "L": 300,
        "num_iters": 30,
        "batch_size": 1,
        "num_epochs": 500,
        "normalize": True,
        "lr": 0.1,
        "lr_decay": 0.8,
        "lr_step": 10,
        "noiseSTD": 20,
        "shuffle": True,
        "test_path": "../data/test_img/",
        "info_period": 2000,
        "denoising": True,
        "supervised": True,
        "classification": False,
        "crop_dim": (64, 64),
        "init_with_DCT": True,
        "init_with_saved_file": False,
        # "sigma": 0.03,
        "twosided": True,
        "demean_img": False,
        "loss": "MSE",
        "use_lam": True,
        "lam": 0.1,
        "mode": "gaussian",
    }


@config_ingredient.named_config
def crsae_kernel8_conv64_stride7_fista30():
    hyp = {
        "experiment_name": "crsae_kernel8_conv64_stride7_fista30",
        "dataset": "VOC",
        "network": "CRsAE2D",
        "dictionary_dim": 8,
        "stride": 7,
        "num_conv": 64,
        "L": 50,
        "num_iters": 30,
        "batch_size": 1,
        "num_epochs": 500,
        "normalize": True,
        "lr": 0.1,
        "lr_decay": 0.8,
        "lr_step": 10,
        "noiseSTD": 20,
        "shuffle": True,
        "test_path": "../data/test_img/",
        "info_period": 2000,
        "denoising": True,
        "supervised": True,
        "classification": False,
        "crop_dim": (64, 64),
        "init_with_DCT": True,
        "init_with_saved_file": False,
        # "sigma": 0.03,
        "twosided": True,
        "demean_img": False,
        "loss": "MSE",
        "use_lam": True,
        "lam": 0.3,
        "mode": "gaussian",
    }


@config_ingredient.named_config
def crsae_kernel8_conv64_stride7_fista30_sigmap3():
    hyp = {
        "experiment_name": "crsae_kernel8_conv64_stride7_fista30_sigmap3",
        "dataset": "VOC",
        "network": "CRsAE2D",
        "dictionary_dim": 8,
        "stride": 7,
        "num_conv": 64,
        "L": 50,
        "num_iters": 30,
        "batch_size": 1,
        "num_epochs": 1000,
        "normalize": True,
        "lr": 0.1,
        "lr_decay": 0.7,
        "lr_step": 15,
        "noiseSTD": 20,
        "shuffle": True,
        "test_path": "../data/test_img/",
        "info_period": 2000,
        "denoising": True,
        "supervised": True,
        "classification": False,
        "crop_dim": (64, 64),
        "init_with_DCT": True,
        "init_with_saved_file": False,
        "sigma": 0.03,
        "twosided": True,
        "demean_img": False,
        "loss": "MSE",
        "use_lam": False,
        # "lam": 0.3,
        "mode": "gaussian",
    }


@config_ingredient.named_config
def crsae_kernel8_conv64_stride7_fista30_sigmap3_newdataset():
    hyp = {
        "experiment_name": "crsae_kernel8_conv64_stride7_fista30_sigmap3_newdataset",
        "dataset": "VOC",
        "network": "CRsAE2D",
        "dictionary_dim": 8,
        "stride": 7,
        "num_conv": 64,
        "L": 50,
        "num_iters": 30,
        "batch_size": 1,
        "num_epochs": 500,
        "normalize": True,
        "lr": 0.1,
        "lr_decay": 0.7,
        "lr_step": 25,
        "noiseSTD": 20,
        "shuffle": True,
        "test_path": "../data/test_img/",
        "info_period": 2000,
        "denoising": True,
        "supervised": True,
        "classification": False,
        "crop_dim": (64, 64),
        "init_with_DCT": True,
        "init_with_saved_file": False,
        "sigma": 0.03,
        "twosided": True,
        "demean_img": False,
        "loss": "MSE",
        "use_lam": False,
        # "lam": 0.3,
        "mode": "gaussian",
    }


@config_ingredient.named_config
def crsae_kernel8_conv64_stride7_fista30_sigmap8_unspervised():
    hyp = {
        "experiment_name": "crsae_kernel8_conv64_stride7_fista30_sigmap8_unspervised",
        "dataset": "VOC",
        "network": "CRsAE2D",
        "dictionary_dim": 8,
        "stride": 7,
        "num_conv": 64,
        "L": 50,
        "num_iters": 30,
        "batch_size": 1,
        "num_epochs": 1000,
        "normalize": True,
        "lr": 0.1,
        "lr_decay": 0.8,
        "lr_step": 15,
        "noiseSTD": 20,
        "shuffle": True,
        "test_path": "../data/test_img/",
        "info_period": 2000,
        "denoising": True,
        "supervised": False,
        "classification": False,
        "crop_dim": (64, 64),
        "init_with_DCT": True,
        "init_with_saved_file": False,
        "sigma": 0.08,
        "twosided": True,
        "demean_img": False,
        "loss": "MSE",
        "use_lam": False,
        # "lam": 0.3,
        "mode": "gaussian",
    }


@config_ingredient.named_config
def crsae_kernel8_conv64_stride7_fista30_sigmap82_unspervised():
    hyp = {
        "experiment_name": "crsae_kernel8_conv64_stride7_fista30_sigmap82_unspervised",
        "dataset": "VOC",
        "network": "CRsAE2D",
        "dictionary_dim": 8,
        "stride": 7,
        "num_conv": 64,
        "L": 50,
        "num_iters": 30,
        "batch_size": 1,
        "num_epochs": 1000,
        "normalize": True,
        "lr": 0.2,
        "lr_decay": 0.8,
        "lr_step": 15,
        "noiseSTD": 20,
        "shuffle": True,
        "test_path": "../data/test_img/",
        "info_period": 2000,
        "denoising": True,
        "supervised": False,
        "classification": False,
        "crop_dim": (64, 64),
        "init_with_DCT": True,
        "init_with_saved_file": False,
        "sigma": 0.082,
        "twosided": True,
        "demean_img": False,
        "loss": "MSE",
        "use_lam": False,
        # "lam": 0.3,
        "mode": "gaussian",
    }


@config_ingredient.named_config
def crsae_test_trainable_unsupervised():
    hyp = {
        "experiment_name": "crsae_test_trainable_unsupervised",
        "dataset": "VOC",
        "network": "CRsAE2DTrainableBias",
        "dictionary_dim": 8,
        "stride": 4,
        "num_conv": 64,
        "L": 2500,
        "num_iters": 50,
        "batch_size": 1,
        "num_epochs": 1000,
        "normalize": True,
        "lr": 0.05,
        "lr_decay": 0.8,
        "lr_step": 10,
        "lr_lam": 0.05,
        "noiseSTD": 20,
        "shuffle": True,
        "test_path": "../data/test_img/",
        "info_period": 100,
        "denoising": True,
        "supervised": False,
        "classification": False,
        "crop_dim": (64, 64),
        "init_with_DCT": True,
        "init_with_saved_file": False,
        # "sigma": 0.03,
        "twosided": True,
        "demean_img": False,
        "loss": "MSE",
        "use_lam": True,
        "lam": 63,
        "mode": "gaussian",
        "trainable_bias": True,
        "sigma": 0.07843,
        "delta": 500,
    }


@config_ingredient.named_config
def crsae_kernel8_conv64_stride7_fista30_sigmap25():
    hyp = {
        "experiment_name": "crsae_kernel8_conv64_stride7_fista30_sigmap25",
        "dataset": "VOC",
        "network": "CRsAE2D",
        "dictionary_dim": 8,
        "stride": 7,
        "num_conv": 64,
        "L": 50,
        "num_iters": 30,
        "batch_size": 1,
        "num_epochs": 1000,
        "normalize": True,
        "lr": 0.1,
        "lr_decay": 0.8,
        "lr_step": 15,
        "noiseSTD": 20,
        "shuffle": True,
        "test_path": "../data/test_img/",
        "info_period": 2000,
        "denoising": True,
        "supervised": True,
        "classification": False,
        "crop_dim": (64, 64),
        "init_with_DCT": True,
        "init_with_saved_file": False,
        "sigma": 0.025,
        "twosided": True,
        "demean_img": False,
        "loss": "MSE",
        "use_lam": False,
        # "lam": 0.3,
        "mode": "gaussian",
    }


@config_ingredient.named_config
def crsae_kernel8_conv144_stride7_fista30_sigmap3():
    hyp = {
        "experiment_name": "crsae_kernel8_conv144_stride7_fista30_sigmap3",
        "dataset": "VOC",
        "network": "CRsAE2D",
        "dictionary_dim": 8,
        "stride": 7,
        "num_conv": 144,
        "L": 100,
        "num_iters": 30,
        "batch_size": 1,
        "num_epochs": 1000,
        "normalize": True,
        "lr": 0.1,
        "lr_decay": 0.8,
        "lr_step": 15,
        "noiseSTD": 20,
        "shuffle": True,
        "test_path": "../data/test_img/",
        "info_period": 2000,
        "denoising": True,
        "supervised": True,
        "classification": False,
        "crop_dim": (64, 64),
        "init_with_DCT": True,
        "init_with_saved_file": False,
        "sigma": 0.03,
        "twosided": True,
        "demean_img": False,
        "loss": "MSE",
        "use_lam": False,
        # "lam": 0.3,
        "mode": "gaussian",
    }


@config_ingredient.named_config
def paper_crsae_kernel8_conv64_stride7_fista30_sigmap3():
    hyp = {
        "experiment_name": "paper_crsae_kernel8_conv64_stride7_fista30_sigmap3",
        "dataset": "VOC",
        "network": "CRsAE2D",
        "dictionary_dim": 8,
        "stride": 7,
        "num_conv": 64,
        "L": 50,
        "num_iters": 30,
        "batch_size": 1,
        "num_epochs": 500,
        "normalize": True,
        "lr": 0.1,
        "lr_decay": 0.7,
        "lr_step": 10,
        "noiseSTD": 20,
        "shuffle": True,
        "test_path": "../data/test_img/",
        "info_period": 2000,
        "denoising": True,
        "supervised": True,
        "classification": False,
        "crop_dim": (64, 64),
        "init_with_DCT": True,
        "init_with_saved_file": False,
        "sigma": 0.03,
        "twosided": True,
        "demean_img": False,
        "loss": "MSE",
        "use_lam": False,
        # "lam": 0.3,
        "mode": "gaussian",
    }


@config_ingredient.named_config
def paper_crsae_kernel8_conv64_stride7_fista30_sigmap3_initrandom():
    hyp = {
        "experiment_name": "paper_crsae_kernel8_conv64_stride7_fista30_sigmap3_initrandom",
        "dataset": "VOC",
        "network": "CRsAE2D",
        "dictionary_dim": 8,
        "stride": 7,
        "num_conv": 64,
        "L": 50,
        "num_iters": 30,
        "batch_size": 1,
        "num_epochs": 100,
        "normalize": True,
        "lr": 0.1,
        "lr_decay": 0.7,
        "lr_step": 10,
        "noiseSTD": 20,
        "shuffle": True,
        "test_path": "../data/test_img/",
        "info_period": 2000,
        "denoising": True,
        "supervised": True,
        "classification": False,
        "crop_dim": (64, 64),
        "init_with_DCT": False,
        "init_with_saved_file": False,
        "sigma": 0.03,
        "twosided": True,
        "demean_img": False,
        "loss": "MSE",
        "use_lam": False,
        # "lam": 0.3,
        "mode": "gaussian",
    }


@config_ingredient.named_config
def paper_crsae_kernel8_conv64_stride7_fista30_sigmap83_unsupervised():
    hyp = {
        "experiment_name": "paper_crsae_kernel8_conv64_stride7_fista30_sigmap83_unsupervised",
        "dataset": "VOC",
        "network": "CRsAE2D",
        "dictionary_dim": 8,
        "stride": 7,
        "num_conv": 64,
        "L": 50,
        "num_iters": 30,
        "batch_size": 1,
        "num_epochs": 500,
        "normalize": True,
        "lr": 0.1,
        "lr_decay": 0.7,
        "lr_step": 10,
        "noiseSTD": 20,
        "shuffle": True,
        "test_path": "../data/test_img/",
        "info_period": 2000,
        "denoising": True,
        "supervised": False,
        "classification": False,
        "crop_dim": (64, 64),
        "init_with_DCT": True,
        "init_with_saved_file": False,
        "sigma": 0.083,
        "twosided": True,
        "demean_img": False,
        "loss": "MSE",
        "use_lam": False,
        # "lam": 0.3,
        "mode": "gaussian",
    }


@config_ingredient.named_config
def paper_crsae_kernel8_conv64_stride4_fista50_lam24_supervised_trainlam():
    hyp = {
        "experiment_name": "paper_crsae_kernel8_conv64_stride4_fista50_lam24_supervised_trainlam",
        "dataset": "VOC",
        "network": "CRsAE2DTrainableBias",
        "dictionary_dim": 8,
        "stride": 4,
        "num_conv": 64,
        "L": 2500,
        "num_iters": 50,
        "batch_size": 1,
        "num_epochs": 500,
        "normalize": True,
        "lr": 0.05,
        "lr_decay": 0.7,
        "lr_step": 5,
        "lr_lam": 0.1,
        "noiseSTD": 20,
        "shuffle": True,
        "test_path": "../data/test_img/",
        "info_period": 300,
        "denoising": True,
        "supervised": True,
        "classification": False,
        "crop_dim": (64, 64),
        "init_with_DCT": True,
        "init_with_saved_file": False,
        # "sigma": 0.03,
        "twosided": True,
        "demean_img": False,
        "loss": "MSE",
        "use_lam": True,
        "lam": 24.4,
        "mode": "gaussian",
        "trainable_bias": True,
        "sigma": 0.07843,
        "delta": 500,
    }


@config_ingredient.named_config
def paper_crsae_kernel8_conv64_stride4_fista50_lam68_unsupervised_trainlam():
    hyp = {
        "experiment_name": "paper_crsae_kernel8_conv64_stride4_fista50_lam68_unsupervised_trainlam",
        "dataset": "VOC",
        "network": "CRsAE2DTrainableBias",
        "dictionary_dim": 8,
        "stride": 4,
        "num_conv": 64,
        "L": 2500,
        "num_iters": 50,
        "batch_size": 1,
        "num_epochs": 500,
        "normalize": True,
        "lr": 0.1,
        "lr_decay": 0.7,
        "lr_step": 5,
        "lr_lam": 0.1,
        "noiseSTD": 20,
        "shuffle": True,
        "test_path": "../data/test_img/",
        "info_period": 300,
        "denoising": True,
        "supervised": False,
        "classification": False,
        "crop_dim": (64, 64),
        "init_with_DCT": True,
        "init_with_saved_file": False,
        # "sigma": 0.03,
        "twosided": True,
        "demean_img": False,
        "loss": "MSE",
        "use_lam": True,
        "lam": 68,
        "mode": "gaussian",
        "trainable_bias": True,
        "sigma": 0.07843,
        "delta": 500,
    }


@config_ingredient.named_config
def paper_crsae_kernel8_conv64_stride1_fista50_lam68_unsupervised_trainlam():
    hyp = {
        "experiment_name": "paper_crsae_kernel8_conv64_stride1_fista50_lam68_unsupervised_trainlam",
        "dataset": "VOC",
        "network": "CRsAE2DTrainableBias",
        "dictionary_dim": 8,
        "stride": 1,
        "num_conv": 64,
        "L": 2500,
        "num_iters": 50,
        "batch_size": 1,
        "num_epochs": 500,
        "normalize": True,
        "lr": 0.1,
        "lr_decay": 0.7,
        "lr_step": 5,
        "lr_lam": 0.1,
        "noiseSTD": 20,
        "shuffle": True,
        "test_path": "../data/test_img/",
        "info_period": 2000,
        "denoising": True,
        "supervised": False,
        "classification": False,
        "crop_dim": (64, 64),
        "init_with_DCT": True,
        "init_with_saved_file": False,
        # "sigma": 0.03,
        "twosided": True,
        "demean_img": False,
        "loss": "MSE",
        "use_lam": True,
        "lam": 68,
        "mode": "gaussian",
        "trainable_bias": True,
        "sigma": 0.07843,
        "delta": 500,
    }


@config_ingredient.named_config
def pascalVOC_lcsc():
    hyp = {
        "experiment_name": "pascalVOC_lcsc",
        "dataset": "VOC",
        "network": "LCSC2D",
        "dictionary_dim": 7,
        "num_conv": 64,
        "stride": 1,
        "L": 10,
        "lam": 0.1,
        "num_iters": 3,
        "batch_size": 1,
        "num_epochs": 100,
        "info_period": 1000,
        "normalize": False,
        "supervised": True,
        "lr": 0.1,
        "lr_decay": 0.7,
        "lr_step": 10,
        "noiseSTD": 20,
        "init_with_DCT": True,
        "init_with_saved_file": False,
        "shuffle": True,
        "test_path": "../data/test_img/",
        "crop_dim": (64, 64),
        "mode": False,
    }
